name: "Plan"
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      ARM_CLIENT_ID: { required: true }
      ARM_SUBSCRIPTION_ID: { required: true }
      ARM_TENANT_ID: { required: true }
      ARM_CLIENT_SECRET: { required: true }



jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
      ARM_CLIENT_SECRET: ${{ vars.ARM_CLIENT_SECRET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Init
        run: terraform init

      - name: Validate
        run: terraform validate

      - name: Plan
        run: |
          terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }}
          terraform plan -var-file="variables/${{ inputs.environment }}.tfvars"